### ISSUE TITLE
Some questions about the plugin

### ISSUE THREAD

**Issue by anilgky** [UraraReika/jet-woo-builder-custom-product-badges#1]
Hello,

first of all thank you for the plugin, we use it in our store. I have a few questions about the plugin:

1. Is the plugin not yet completely official from Crocoblocks? We could not find it on the website and the instructions to add more badges I found very difficult on Git (A developer installed it in the past with which we no longer work). 

2. Will the plugin be updated in the future and can for example badges be added more easily?

3. We have created a new badge "Sold Out". Could this be automated so that the Sold Out badge automatically shows up in Collections ( Not product page) when a product is sold out?  

4. We have added several badges, is the code below right to add more than one badge?

```
    add_filter( 'jet-woo-builder-cpb/integration/badges', '__ayen_theme_prefix_extend_custom_badges_list' );

    function __ayen_theme_prefix_extend_custom_badges_list( $list ) {
    	$list['Coming Soon'] = 'Coming soon';
		$list['Sold Out'] = 'Sold out';
        return $list;
    }
```

Thank you and kind regards
Anil

**Comment by UraraReika** [comment]
Hello @anilgky !

1 - I'm one of Crocoblock developers so this is official dev tools plugin. Right now only one way to create new badges. 
2 - Yes, it will.
3 - It can be done only with some custom code.
4 - Yes.

**Comment by anilgky** [comment]
Hello @UraraReika ,

Thank you very much for your answers, you are all doing a great job!

I hope you are all well, take care of yourselves.

Many greetings from Germany
Anil
