### ISSUE TITLE
Custom badge on single product page

### ISSUE THREAD

**Issue by maiestro21** [UraraReika/jet-woo-builder-custom-product-badges#3]
Is there any possibility to show the badge on the jetwoo single page?
![image](https://user-images.githubusercontent.com/8317526/168807267-d9b7542a-023f-4e68-8761-0c98b5fbc7cb.png)

**Comment by UraraReika** [comment]
Hello @maiestro21 !

We have a product with sale price https://tppr.me/mbRbt. In elementor we use Single Sale Badge widget with macros `%percentage_sale%` https://tppr.me/nhnsD and this we can see in the frontend https://tppr.me/ZWZgO.

If you have some difficulties with this please [contact](https://support.crocoblock.com/support/home/ ) our support team. Thank you!

**Comment by maiestro21** [comment]
Hello,

First, thanks for the fast reply.

Yes, the sales badge appears on the single page, but my question was releated to the others custom badges.

For example, if a product has sales badge and also ,hot' badge, how can I make both of them appear on the single product page?

Thanks a lot!

**Comment by UraraReika** [comment]
For now there is no any way. But in nearest future with the help of this plugin https://tppr.me/HFQip you can do it https://crocoblock.com/freemium/tools/.
