### ISSUE TITLE
Custom Product Badges not work

### ISSUE THREAD

**Issue by cazper57** [UraraReika/jet-woo-builder-custom-product-badges#4]
the plugin does not work anymore, i do not know why
the functions.php I checked /elmentor / product editing are the badges set and selected
all other plugins were already deactivated and tested

I hope you can help me
many greetings

**Comment by UraraReika** [comment]
Hello @cazper57 ! Thanks for the feedback.

Today we updated this plugin and you can fell free to download it and install on your site. Please check [changelog](https://github.com/UraraReika/jet-woo-builder-custom-product-badges) for it to look whats new appears.

From now on you can add new badges strait from [admin area](https://tppr.me/AYcbZ) without coding as well as delete them. The proses of assigning stay the same. Although the list of widgets where you can use it become bigger ( Products Grid, Products List, Archive Sale Badge and Single Sale Badge).

**Comment by cazper57** [comment]
The new version works ! Nice one ! thanks
