### ISSUE TITLE
Display only 1 discount custom badge value

### ISSUE THREAD

**Issue by iconicagency** [UraraReika/jet-woo-builder-custom-product-badges#6]
Hello dev team.

I have the following problem. My website has Jet Woo Builder installed and JetWooBuilder - Custom Product Badges installed to create additional badges for products.
In the product builder page, I have enabled the custom badge function and enabled the badge label in the style "Sale %percentage_sale%".
However, when displayed, the sale numbers are arranged in reverse, meaning the highest discounts are displayed first. I want to display only the lowest "%percentage_sale%", how can I do that?
Thank you.

![FireShot Capture 081 - Edit _Trang Sức Kim Cương_ with Elementor - bemiie com](https://github.com/UraraReika/jet-woo-builder-custom-product-badges/assets/69346173/f2e24fcb-82ce-43f3-b35c-499f59b571a7)

**Comment by UraraReika** [comment]
Hello @tinhocngoisao!

You can add this code snippet in your child theme `functions.php` file

```
add_filter( 'jet-woo-builder/macros/macros-list', function( $macros ) {
	$macros['percentage_sale_min'] = 'get_percentage_sale_min';
	return $macros;
} );

function get_percentage_sale_min() {
	global $product;

	$percentage_sale = '';
	$precision       = 0;

	if ( 'variable' === $product->get_type() ) {
		$prices = jet_woo_builder()->macros->sort_variation_price( $product );

		if ( $prices['regular_min'] > 0 && $prices['regular_max'] > 0 ) {
			$percentage_min  = round( 100 - ( $prices['sale_max'] / $prices['regular_max'] * 100 ), $precision );
			$percentage_max  = round( 100 - ( $prices['sale_min'] / $prices['regular_min'] * 100 ), $precision );
			$percentage_sale = $percentage_min ?: $percentage_max;
		}
	} else {
		$regular_price = (float) $product->get_regular_price();
		$sale_price    = (float) $product->get_price();

		if ( $sale_price > 0 && $regular_price > 0 ) {
			$percentage_sale = round( 100 - ( $sale_price / $regular_price * 100 ), $precision );
		}
	}

	return $percentage_sale ? $percentage_sale . '&#37;' : '';
}
```

And then in editor control use `%percentage_sale_min%` instead `%percentage_sale%`

**Comment by iconicagency** [comment]
Thansk you.

**Comment by iconicagency** [comment]
I want to display the biggest sale price, how do I change it?

**Comment by iconicagency** [comment]
@UraraReika Help me

**Comment by UraraReika** [comment]
First of all you need to add new macros `percentage_sale_max` like this:

```php
add_filter( 'jet-woo-builder/macros/macros-list', function( $macros ) {
    $macros['percentage_sale_min'] = 'get_percentage_sale_min';
    $macros['percentage_sale_max'] = 'get_percentage_sale_max';

    return $macros;
} );
```

Then add callback function for it:

```php
function get_percentage_sale_max() {
    global $product;

    $percentage_sale = '';
    $precision       = 0;

    if ( 'variable' === $product->get_type() ) {
        $prices = jet_woo_builder()->macros->sort_variation_price( $product );

         if ( $prices['regular_min'] > 0 && $prices['regular_max'] > 0 ) {
             $percentage_max  = round( 100 - ( $prices['sale_min'] / $prices['regular_min'] * 100 ), $precision );
             $percentage_sale = $percentage_max;
         }
    } else {
        $regular_price = (float) $product->get_regular_price();
        $sale_price    = (float) $product->get_price();

        if ( $sale_price > 0 && $regular_price > 0 ) {
            $percentage_sale = round( 100 - ( $sale_price / $regular_price * 100 ), $precision );
        }
    }

    return $percentage_sale ? $percentage_sale . '&#37;' : '';
}
```
And then in editor control use %percentage_sale_max% instead %percentage_sale%

**Comment by iconicagency** [comment]
Thanks you

**Comment by iconicagency** [comment]
@UraraReika 

Hello
After adding your code, I saw a change. However, the price percentage is not very accurate. Can you assist me?
This is my website: https://bemiie.com/nhan-kim-cuong-nu/
This product: https://bemiie.com/san-pham/nhan-nu-cathedral-heart-cut/
There are signs I'm offering up to 50% off, but the biggest sale is only 45% off.

**Comment by UraraReika** [comment]
We have checked your request and everything seems to be working correctly. Perhaps this is related to your site. Please [contact](https://support.crocoblock.com/support/home/ ) our support team.

Thank you!

**Comment by iconicagency** [comment]
Thanks you.
